version: "3.9"

services:
  db-beacon:
    image: mongo
    hostname: db-beacon
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  db-beacon-load:
    image: mongo
    links:
      - db-beacon
    volumes:
      - ./db/CINECA_synthetic_cohort_EUROPE_UK1/bff:/data  
      - ./db/bff2mongodb_container.sh:/bff2mongodb.sh  
    command: bash bff2mongodb.sh
    depends_on:
      - db-beacon

  web:
    build: .
    command:
      - /bin/sh
      - -c
      - |
          echo "sleep for 60sec"
          sleep 60 
          python app/manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - DATABASE_NAME=beacon
      - DATABASE_HOST=db-beacon
      - DATABASE_PORT=27017
      - USERNAME=root
      - PASSWORD=example
    depends_on:
      - db-beacon

